

export enum PermissionStatus {
    CHEKING = 'CHEKING',
    GRANTED = 'GRANTED',
    DENIED = 'DENIED',
    BLOCKED = 'BLOCKED',
    LIMITED = 'LIMITED',
    UNAVAILABLE = 'UNAVAILABLE',
    UNDETERMINED = 'UNDETERMINED',    
}